select *
from ProjectPortfolio..SalesData;

-- checking for duplicates

with cte as (select *, ROW_NUMBER() over(partition by [order id], 
                            [order date], [purchase address], 
                            month, city,
                            hour order by product) as [row num]
from ProjectPortfolio..SalesData)
select *
from cte
where [row num] >1

--Formatted the order date column to date

select [Order Date]
from ProjectPortfolio..SalesData;

alter table projectportfolio..salesdata
alter column [order date] date

-- Splitting the Purchase Address to separate columns(address and country zipcode)

select [purchase address], PARSENAME(replace([purchase address], ',','.'),1)
from ProjectPortfolio..SalesData

select [purchase address], PARSENAME(replace([purchase address], ',','.'),3)
from ProjectPortfolio..SalesData

-- creating columns for the extracted address data
alter table projectportfolio..salesdata
add Purchase_Address nvarchar(255)
alter table projectportfolio..salesdata
add zip_code nvarchar(255)

update ProjectPortfolio..SalesData
set Purchase_Address = PARSENAME(replace([purchase address], ',','.'),3)

update ProjectPortfolio..SalesData
set zip_code = PARSENAME(replace([purchase address], ',','.'),1)

select [quantity ordered]*[price each] totalsales
from ProjectPortfolio..SalesData

alter table projectportfolio..salesdata
add adjustedsales float



update ProjectPortfolio..SalesData
set adjustedsales = [quantity ordered]*[price each]

--Removing unused column(Sales)

alter table projectportfolio..salesdata
drop column sales


--Identifying peak of sales by date

select [Order Date] as date, sum(adjustedsales) as total_sales
from ProjectPortfolio..SalesData
group by [Order Date]
order by 2 desc

-- 10 Best performing Products by revenue

select top 10 product as items, sum(adjustedsales) as total_sales
from ProjectPortfolio..SalesData
group by Product 
order by 2 desc

select count(product)
from ProjectPortfolio..SalesData

--Worst performing Products by revenue

select product as items, sum(adjustedsales) as total_sales
from ProjectPortfolio..SalesData
group by Product 
order by 2 


-- Total sales across all products

select sum(adjustedsales) as totalsales
from ProjectPortfolio..SalesData
--order by 2 desc

--Breakdown of Total revenue generated by each product

select product,sum(adjustedsales) as Total_by_products
from ProjectPortfolio..SalesData
group by Product
order by 2 desc

--top 10 Customers spending the most with us

select top 10 [order id], sum(adjustedsales) as total_sales
from ProjectPortfolio..SalesData
group by [Order ID]
order by 2 desc

--% of grand total spent by customers

select (adjustedsales/sum(adjustedsales))*100 as percentage_by_customer_spent
from ProjectPortfolio..SalesData
group by adjustedsales
order by 1 desc

-- revenue growth

select month, sum(adjustedsales) 
from ProjectPortfolio..SalesData
group by month
order by 2 desc

-- A rolling total across all products over time
with total_table as (select *, sum(adjustedsales) over(partition by product order by [order id]) as rollingtotal
from ProjectPortfolio..SalesData)
select [order id], [order date], product, adjustedsales, rollingtotal
from total_table













